//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkupEDM.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int Id_Cuenta { get; set; }
        public long NumeroCuenta { get; set; }
        public decimal SaldoCuenta { get; set; }
        public int IdCliente { get; set; }
        public bool Predeterminada { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
