//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkupEDM.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public string Id_Envio { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string CodigoRemitente { get; set; }
        public int ClientesId { get; set; }
        public int EstadoEnvio { get; set; }
        public int MonedaId_Moneda { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual EstadoEnvio EstadoEnvio1 { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
