//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkupEDM.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public string Id_Envio { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string CodigoRemitente { get; set; }
        public int ClientesId { get; set; }
        public int EstadoEnvio { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual EstadoEnvio EstadoEnvio1 { get; set; }
    }
}
