//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkupEDM.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public int Id_Cambio { get; set; }
        public decimal CambioDia { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public int MonedaId { get; set; }
    
        public virtual Moneda Moneda { get; set; }
    }
}
